'use client';

import React, { useState } from 'react';
import ModuleLayout from '@/components/layout/ModuleLayout';
import { Clock, Download, Search, CheckCircle2, ArrowUpRight } from 'lucide-react';

const reportsSubnav = [
  { label: 'All Reports', href: '/reports' },
  { label: 'Create Report', href: '/reports/create' },
  { label: 'Export Engine', href: '/reports/export' },
  { label: 'Archive History', href: '/reports/history' },
];

const archive = [
  { id: 'rep-hist-1', title: 'Monthly Cluster SLA Report (July 2026)', date: 'Aug 1, 2026', size: '2.4 MB', author: 'System' },
  { id: 'rep-hist-2', title: 'Security Pen-Test & Red-Teaming Report', date: 'Jul 15, 2026', size: '4.8 MB', author: 'Agent 3 Critic' },
  { id: 'rep-hist-3', title: 'Initial pgvector Benchmark Specification', date: 'Jun 28, 2026', size: '1.2 MB', author: 'Jaswant Karun' },
];

export default function ReportsHistoryPage() {
  const [search, setSearch] = useState('');

  const filtered = archive.filter(a => a.title.toLowerCase().includes(search.toLowerCase()));

  return (
    <ModuleLayout
      title="Archived Reports & Historical Audits"
      subtitle="Historical repository of past cluster evaluations, compliance filings, and whitepapers"
      subnav={reportsSubnav}
    >
      <div className="space-y-6">
        <div className="flex items-center justify-between gap-4 p-4 rounded-2xl bg-slate-900/60 border border-slate-800">
          <div className="relative w-full max-w-md">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search historical archives..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs sm:text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <span className="text-xs text-slate-400 font-mono">{filtered.length} Archived Files</span>
        </div>

        <div className="space-y-3">
          {filtered.map(item => (
            <div
              key={item.id}
              className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/80 hover:border-slate-700 transition-all flex items-center justify-between gap-4"
            >
              <div>
                <h4 className="text-sm font-semibold text-white">{item.title}</h4>
                <div className="flex items-center gap-2 text-xs text-slate-400 mt-0.5">
                  <span>{item.date}</span>
                  <span>•</span>
                  <span>{item.size}</span>
                  <span>•</span>
                  <span>Generated by {item.author}</span>
                </div>
              </div>

              <button
                onClick={() => alert(`Downloading archive ${item.title}`)}
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
                title="Download Archive"
              >
                <Download className="w-4 h-4" />
              </button>
            </div>
          ))}
        </div>
      </div>
    </ModuleLayout>
  );
}
